### PR TITLE
Add Zenodo auto-deposit for DOI registration

### PR DESCRIPTION
**Pull request by pkgw**
### Overview

Add automated Zenodo deposition to mint DOIs for pywwt releases.

Minting DOIs implies maintaining a formal author list. For that, I've included everyone who's ever committed to the repository, alphabetically by family name. But I won't list people without their permission. **If you'd like to be included as an author, please comment on this PR to that effect**, and review what I've put for your name, affiliation, and ORCID:

- [x] @Carifio24
- [x] @vga101
- [x] @imbasimba 
- [x] @ojustino 
- [x] @astrofrog
- [x] @jsub1
- [x] @pkgw (me)
- [x] @jzuhone

It might take me a couple of tries to get the CI/CD automation to fully work, but hopefully it will be straightforward since I've gotten it going for the Cranko tool itself.

### CODE REVIEW

**Comment by Carifio24** [comment]
I'd like to be added as an author! My ORCID is 0000-0002-7759-2601.

**Comment by ojustino** [comment]
Hi @pkgw, thanks for including me. Please add ORCID 0000-0002-4679-5692.

**Comment by imbasimba** [comment]
@pkgw Happy to be included! The information you've added about me is correct.

**Comment by jzuhone** [comment]
Also, please change my name to "John"

**Comment by astrofrog** [comment]
Thanks, this looks good to me! 👍

**Comment by pkgw** [comment]
I got signoff from @jsub1 over email.

**Pull request merged**
