### PR TITLE
Added validation for frames in TableLayer

### PR DESCRIPTION
**Pull request by ojustino**
Settling a to-do item in `layers.py`.

### CODE REVIEW

**Comment by ojustino** [comment]
I added another commit that explicitly lets the user know which of the keys for their calls to `TableLayer`, `ImageLayer`, or `Annotation` cause a `KeyError` for being invalid. Before, the messages were more vague in saying that "a key" was not valid, even if there were multiple offenders.

**Comment by astrofrog** [comment]
@ojustino - can you rebase to include the latest fixes to the CI? (https://github.com/WorldWideTelescope/pywwt/pull/196)

**Comment by ojustino** [comment]
@astrofrog I'm getting back on track and rebased this branch.

**Comment by astrofrog** [comment]
@ojustino - sorry for not getting back to this sooner! Two requests before merging this:

* Could you make a helper function that basically does:

```
        mismatch = [key for key in kwargs if key not in self.trait_names()]
        if mismatch:
            raise KeyError('Key{0} {1} do{2}n\'t match any layer trait name'
                           .format('s' if len(mismatch) > 1 else '',
                                   mismatch,
                                   '' if len(mismatch) > 1 else 'es'))
```

since this block of code appears three times? You could make the function take a class and the kwargs and it could validate against the trait names of that class.

* Could you rebase this PR to include the latest improvements to the Continuous Integration?

**Comment by ojustino** [comment]
@astrofrog Rebased. I added helper functions like you asked in both files. Did you mean for the function to appear once per file? The three instances are spread across two files, so in defining the function twice we only remove one instance of that block of code.

**Comment by astrofrog** [comment]
@ojustino - can you define the function once in ``pywwt/utils.py`` and import it from there into both files?

**Comment by ojustino** [comment]
@astrofrog OK, the code is now condensed.

**Pull request merged**
