### PR TITLE
Installation and jupyter doc tweaks

### PR DESCRIPTION
**Pull request by ojustino**
I added minimum-version information about Jupyter-affiliated packages from #149 (hopefully resolving #80 as well) to the installation doc.

I also changed the image in the jupyter doc since it assigned `WWTJupyterWidget()` to `widget` while the text assumes it was assigned to `wwt`. The standard has been to use `wwt`, so I changed the image to match.

### CODE REVIEW

**Comment by ojustino** [comment]
The quality of the image is sub-optimal, so I'll work on changing that...

**Comment by ojustino** [comment]
OK, this should be ready to go once reviewed.

**Comment by pkgw** [comment]
Can you keep the image file as a JPG rather than PNG? The difference in file size is nontrivial.

If you're comfortable rewriting Git history, it would be good to rewrite it to not add the PNG file and force-push to this branch. Otherwise the addition of the PNG file will add 1.5 MB to the repository size that will hang around forever.

**Comment by ojustino** [comment]
@pkgw OK, the PNG file is erased from the history of this branch.

**Pull request merged**
