### PR TITLE
New way to add image layers, with stretch controls

### PR DESCRIPTION
**Pull request by astrofrog**
This adds a new way of adding image layers via the LayerManager instead of ``load_fits_data``, and provides ways of setting the min/max/stretch on the images.

I plan to add tests and documentation for this shortly.

### CODE REVIEW

**Comment by pkgw** [comment]
AppVeyor is failing due to a missing `reproject` module — is there a list of module deps in the AppVeyor file that's gotten out of sync with the rest of the project?

(If so, for these kinds of redundancies I like to add a comment to the effect of "If you modify this list, also modify other/file/a and other/file/y too" in each file containing the redundant information.)

**Comment by astrofrog** [comment]
Yeah it's frustrating to have lists of dependencies defined in multiple places - I'm planning to update the CI config so that dependencies have to be defined only once, in setup.cfg.

**Comment by ojustino** [comment]
@astrofrog I'm hoping to test this soon, but this should help address #85 and #113, correct?

**Comment by ojustino** [comment]
@astrofrog I tried this with some small FITS files and had success. It's cool to finally have these things working. If you don't do it yourself while tidying up the code and writing documentation, I can merge the image and table-related events in `wwt_json_api.js`.

Is there still a use for `wwt.load_fits_data()`? It looks to me like `wwt.layers.add_image_layer` has all of its relevant functionality.

**Comment by astrofrog** [comment]
@ojustino - I was originally keeping ``load_fits_data`` for backward-compatibility but thinking about it more I don't think it's going to matter, since the function wasn't previously very useful without stretch controls so I'm not sure if anyone really used it (it was also very restrictive in terms of projection). So I've removed it.

**Comment by astrofrog** [comment]
The CI failures are unrelated, I think I'm going to have to update the baseline images for the tests as there must have been some changes in the rendering recently.

**Pull request merged**
