### PR TITLE
Add DECaPS2 to default pywwt surveys

### PR DESCRIPTION
**Pull request by Carifio24**
I got a request to expose the DECaPS2 RGB survey to `glue-wwt`. The most straightforward way to do that is to add it to the default `pywwt` surveys, and then `pywwt` users can access it as well. The WTML tag here is taken verbatim from the default webclient surveys.

### CODE REVIEW

**Comment by pkgw** [comment]
Closing and reopening to retrigger the CI — I think it was affected by a GitHub service incident yesterday.

**Comment by pkgw** [comment]
@Carifio24 Oh, I see the problem — this PR was asking to merge into the `gh-pages` branch, not `master`, for some reason. I think I can change that myself.

**Comment by pkgw** [comment]
Oops, I guess it was supposed to be like that, and GitHub won't let me reopen it. Can you please re-file? I'll try to fix the ReadTheDocs configuration to ignore this branch.

**Comment by pkgw** [comment]
Hmm, as far as I can tell, there's no way to tell the ReadTheDocs integration to ignore PRs to unusual branches like `gh-pages`. Which is basically OK — we can just ignore the failure. It's just not as tidy as it could be.

**Comment by Carifio24** [comment]
@pkgw I've re-filed this as #374.

**Pull request closed without merging**
