### PR TITLE
Update ecliptic grid color default

### PR DESCRIPTION
**Pull request by Carifio24**
With all the colors getting exposed in #355, I accidentally gave the ecliptic grid the wrong starting color (maybe got it mixed up with the ecliptic color?) - it should be [green](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/wwtlib/Settings.cs#L358), rather than blue, to match the engine. This PR fixes that.

### CODE REVIEW

**Comment by Carifio24** [comment]
The CI failures are unrelated, and seem to be an issue with the Jupyter `notebook` package - version 7.0.0 of that package released yesterday.

There's a [migration guide](https://jupyter-notebook.readthedocs.io/en/stable/migrating/frontend-extensions.html) for Notebook 7, but updating sounds like it could be a real task - maybe we should pin for now?

**Comment by pkgw** [comment]
Well, Notebook 7 is a pretty major update, but we don't actually use the `notebook` module much — just some infrastructure references in `jupyter_server` and `jupyter_relay`, for the main package. It looks like the build errors are mostly the `.check_enabled.py` helper script, which hopefully should be easy to update to be compatible with both major versions.

**Comment by Carifio24** [comment]
So from what I can see, we're still getting errors because `jupyter_contrib_core` (pulled in through `jupyter_contrib_extensions` [here](https://github.com/WorldWideTelescope/pywwt/blob/master/ci/azure-build-and-test.yml#L147))  hasn't been updated for Notebook 7 (i.e. they need to do what you just added in the last commit). See e.g. [here](https://github.com/Jupyter-contrib/jupyter_contrib_core/blob/master/src/jupyter_contrib_core/notebook_compat/nbextensions.py) (their `_compat.nbextensions` also imports `notebook` directly).

**Comment by pkgw** [comment]
Things seemed to be working for me with `notebook >= 7` and without that package installed, so I think the question is, can we perhaps now avoid installing it altogether? Maybe we only need one of its dependencies?

**Comment by Carifio24** [comment]
That explicit installation inside the CI workflow is the only reference I can find to `jupyter_contrib_nbextensions`. It was added in [this commit](https://github.com/WorldWideTelescope/pywwt/commit/46cc64538c19de7536812b4c67b8cd5bf463011a), so I'm assuming the `jupyter nbextension list` command was failing without it? (the logs are no longer around). From looking at their list of included extensions, it's not immediately clear to me why that would be, but yeah, maybe we could find the relevant extension and only install that.

**Comment by pkgw** [comment]
Current build failure is a conda problem unrelated to this PR; I think it will be resolved over the next day or so. (I think the current release of conda needs to be yanked and replaced.)

**Comment by pkgw** [comment]
Cool, yes, looks like this problem is dealt with now. The Linux py310 build failed with a segfault while running the test suite (!) but hopefully that is a once-in-a-blue-moon problem ...

**Pull request merged**
