### PR TITLE
Fix compatibilty with Qt6

### PR DESCRIPTION
**Pull request by astrofrog**
### Overview

@Carifio24 I tested out your Qt6 fix suggested in https://github.com/WorldWideTelescope/pywwt/issues/343 and it works fine when using PyWWT inside glue, so from my perspective, this is a sufficient fix.

### Checklist

- [ ] Changed code has some test coverage (or justify why not)
- [ ] Changes in functionality documented (or justify why not)

### CODE REVIEW

**Comment by astrofrog** [comment]
I don't understand the CI setup well enough to be able to add a CI job with PyQt6

**Comment by pkgw** [comment]
I'll see if I can add a CI job although I might not get to it super promptly. If this is sufficiently urgent I'd be OK with merging now and mopping that up later.

**Comment by astrofrog** [comment]
@pkgw - it would be nice to have this in soon as currently I am not able to use glue-wwt correctly on native Python installations on ARM macs (only PyQt6 is supported), but I'll leave it up to you whether to merge now/later.

**Comment by pkgw** [comment]
OK, this has been released on 0.18.1.

**Comment by astrofrog** [comment]
Thank you!

**Pull request merged**
